# commands.sk — Folia 26.2 小游戏服

command /sethub:
    trigger:
        if player is not op:
            send "&c需要 OP" to player
            stop
        set {hub.world} to world of player
        set {hub.x} to floor(x-coordinate of player) + 0.5
        set {hub.y} to floor(y-coordinate of player)
        set {hub.z} to floor(z-coordinate of player) + 0.5
        set {hub.yaw} to yaw of player
        set {hub.pitch} to pitch of player
        send "&a大厅坐标已设置并保存到磁盘！" to player
        send "&7  世界: &f%{hub.world}%" to player
        send "&7  坐标: &f%{hub.x}% , %{hub.y}% , %{hub.z}%" to player

command /hub [<offline player>]:
    aliases: /lobby, /l
    trigger:
        if arg-1 is set:
            if player is not op:
                send "&c需要 OP" to player
                stop
            if {hub.world} is not set:
                send "&c大厅未设置" to player
                stop
            teleport arg-1 to location({hub.x}, {hub.y}, {hub.z}, {hub.world}, {hub.yaw}, {hub.pitch})
            send "&a已将 %arg-1% 传送到大厅" to player
            send "&b你被管理员传送到了大厅" to arg-1
            stop
        if {hub.world} is not set:
            send "&c大厅未设置，联系管理员 /sethub" to player
            stop
        teleport player to location({hub.x}, {hub.y}, {hub.z}, {hub.world}, {hub.yaw}, {hub.pitch})
        send "&a已传送到大厅！" to player

on load:
    set {_noSatWorlds::*} to "smp-1" and "smp-2"

# ===== 进服：传送 + 菜单钟 + 饱食（列表内不给，列表外给）=====
on join:
    wait 2 ticks
    if {hub.world} is set:
        teleport player to location({hub.x}, {hub.y}, {hub.z}, {hub.world}, {hub.yaw}, {hub.pitch})
        send "&a已传送到大厅！" to player
    else:
        send "&e大厅坐标尚未设置，请联系管理员执行 /sethub" to player

    execute console command "effect give %player% saturation 999999 255 true"

    # 菜单钟：没有才给
    set {_hasMenu} to false
    loop all items in player's inventory:
        if loop-item is a clock:
            if name of loop-item is "&a菜单":
                if lore of loop-item contains "&7右击打开菜单":
                    set {_hasMenu} to true
                    exit loop
    if {_hasMenu} is false:
        give a clock named "&a菜单" with lore "&7右击打开菜单" to player
        send "&a已为你添加菜单物品！右击即可打开大厅菜单" to player
